{
 "title": "Web App Monitor",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "label": "Pod name",
    "query": "label_values(app_version_info, pod)"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(app_request_latency_seconds_bucket, exported_endpoint)"
   },
   {
    "name": "method",
    "label": "HTTP Method",
    "query": "label_values(app_request_latency_seconds_bucket, method)"
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" },
   {
    "name": "error_code",
    "label": "Status code 4xx or 5xx",
    "query": "label_values(app_request_count_total, http_status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Usage by Return",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=~\"2..\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{status=~\"4..|5..\"}",
     "legendFormat": " Errors per second"
    },
    {}
   ]
  },
  {
   "title": "Latency within which $percentile% of requests served",
   "type": "graph",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(app_request_latency_seconds_bucket[$interval])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=~\"4..|5..\"}[$__rate_interval])",
     "legendFormat": "{{ http_status }} {{ pod }} {{ exported_endpoint }}"
    },
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 25 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info",
     "legendFormat": "{{ implementation }} {{ version }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Web App Version -  $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Web App's Uptime - $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 31 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  }
 ]
}